### ISSUE TITLE
List of Matches

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#1]
## Value proposition

As a user
I want to see a list of all soccer matches
so that I can browse the matches for choosing one.

## Description

<img width="473" alt="image" src="https://github.com/sebastianwel/MatchPal/assets/130088331/ea2675a0-287e-4c4f-9440-3c4f4cfb3104">

## Acceptance criteria

- [x] matches are displayed as cards in a list
- [x] each team is presented in the correct order 
  - home at the top, away below in each match
- [x] for each match, the date and kickoff time is displayed
- [x] for each team, a logo is displayed
- [x] matches are ordered by date and time

## Tasks

- [x] Create a feature branch
- [x] Create a teams mock array
- [x] Create a matches mock array
- [x] Create a headline for the List
- [x] Create a Component "MatchCard" for matches
- [x] Create a Component "MatchesList" with matches
- [x] Map the list of matches with the specific teams
- [x] Add a minimal styling to the card component
- [x] Add a minimal styling to the List component

**Comment by FelineHuhn** [comment]
Hey Lukas, really nice first user story! I just have some tiny suggestions for you: 

The value proposition should better be written something more like this: 
*As a* user
*I want to* see a list of all soccer matches
*so that* I can browse the matches for choosing one. 

I really love your Wireframe, very clear. Maybe it would be nice to implement a headline for your page? Without a title it's a little bit meaningless, or? 

Some more suggestions for the acceptance criteria: 

Maybe I would remove the word "all" from the matches, just
- matches are displayed as cards in a list

What defines the "correct" order? It better should be one line for the description of the order. 

Two Typos: 
each

and last, some suggestions for your tasks: 
instead of dataset you could call it mock data? or mock array? Like: 
- create a teams mock array
- create a matches mock array

**Comment by sebastianwel** [comment]
Hey Feline,
thanks for the review. 
However, there is one thing I am not very certain about now. For me this user story is just for mapping the data in a list and building the components in the first place. Why is it necessary to show the headline in the first place? As I understood from our session yesterday, when I showed you my Wireframes you said, we should only show things relating to the scope of the MVP. Therefore I thought here should only be details from the scope of the User Story should be shown. 

I planned to make another user-story for headline and nav-bar seperately and the header already containing a filter method to look the page similar to this:

<img width="274" alt="image" src="https://github.com/sebastianwel/MatchPal/assets/130088331/49b484f1-33fb-4739-8e11-7a2412a52a6b">

Thanks in advance :-)

**Comment by FelineHuhn** [comment]
Hey Sebastian, 
each feature will be deployed after the Review Process. So you always should have a full working app (even it's minimal) after the first user story. My understanding of a working web app is, that a page should always have a headline so I know, on which page or website I am. I mean just a headline and not a whole header (should be an own user story). So the only thing to add would be a `h1` tag with the app name (or something like this) above the rendered List Component. When you later work on your header user story the headline will be replaced of your future `Header` component.

**Comment by FelineHuhn** [comment]
I have two more little suggestions, but it's a matter of taste. Maybe you `Card` and `List` components could have a more descriptive name, like `MatchCard` and `MatchesList`?

**Comment by sebastianwel** [comment]
Thanks, now I understood! 
I also added your suggestions 🤘

**Comment by FelineHuhn** [comment]
Only one tiny tiny thing: It would be more understandable when you write it like this in your A C: 

- each team is presented in the correct order:
   - home at the top, away below in each match

**Comment by sebastianwel** [comment]
Ok, now it should work (hopefully) 😿

**Comment by sebastianwel** [comment]
Ok thanks, changed it. Now it should be fine (hopefully) 😄
I also found a mistake myself, since I said "matches should be ordered by date and time" while the date was not shown in the card. So i I added it in the wireframe. 

I see that user-stories need to be very detailed and the wireframe is important 👍
