### ISSUE TITLE
Add info section to bar details

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#15]
## Value Proposition

**As a** user 
**I want to** be able to have an info section in the bar-details-page 
**so that** I can see more details of the clicked bar.  
​

## Description

![image](https://github.com/sebastianwel/MatchPal/assets/130088331/db17d1d6-b345-41d2-bf95-365649d5b80b)

## Acceptance Criteria

- [ ] when clicking on a bar, besides upcoming matches, an info section can be seen
- [ ] clicking on the info section shows some more bar details like:
    - [ ] Contact-details
    - [ ] Opening-hours
    - [ ] Beer-Prices
    - [ ] Specialities
- [ ] When the info-section is clicked, the name of the section will be highlighted by color

## Tasks

- [ ] Create a new feature/BarDetails-InfoPage
- [ ] Create a new Component BarDetailsInfo
- [ ] BarDetailsInfo receives bar as prop
- [ ] Map in BarDetailsInfo all necessary info
- [ ] Create the link from the bar-details-page to the info-section

**Comment by ThysBat** [comment]
LGTM 🚀 Easy to read, easy to understand, nice!
