### ISSUE TITLE
Add reviews section with form to bar details

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#16]
## Value Proposition

**As a user**
**I want to be able** to have a review section in the bar-details-page
**so that** I can see all reviews of the clicked bar.
​

## Description

![image](https://github.com/sebastianwel/MatchPal/assets/130088331/5a6e03c5-5ad9-45cf-b244-fc291e7b2cff)
​

## Acceptance Criteria

- [ ] when being on the bar-details-page and clicking on the review section the review-section content should be shown
- [ ] a subheading introducing the section will be displayed
- [ ] a list of reviews will be displayed
- [ ] below the list of reviews a comment button should be displayed
- [ ] When clicking the comment button, the comment section should open where the form is displayed
- [ ] the form includes the following inputs:
  - [ ] name of the user
  - [ ] rating
  - [ ] comment
  - [ ] submit-button
- [ ] when clicking the submit-button the comment is displayed in the reviews list
      ​

## Tasks

- [ ] create a new branch feature/BarDetailsReviews
- [ ] create a component to render the reviews list
- [ ] create a component for the review form
- [ ] build the logic for the form-submission
- [ ] add minimal styling

**Comment by julialoeschel** [comment]
Hello there. 
good story, but I this one is a little too big. 
please make sure to have a seperate US for editing and one for deleting comments by the user. 

overall the story is very good!

**Comment by sebastianwel** [comment]
Hey Julia, thanks for the review.
Agree, it's quite big. But I will split it into 2 stories, one for the form with submission and one for the editing and deleting logic since it is a really really small feature imo. 

Thank you!

**Comment by sebastianwel** [comment]
Thanks Julia! 😁
