### ISSUE TITLE
Add delete Button to user-added matches and bars

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#17]
## Value Proposition

**As a** user 
**I want to** be able to delete matches and bars which I added
**so that** I can correct my mistakes if i added something accidently
​

## Description

![image](https://github.com/sebastianwel/MatchPal/assets/130088331/a2578858-9923-45d9-82d4-49a5a40222de)
​

## Acceptance Criteria

- [x] When being on the match-details-page or on the bar-details-page my added items should contain a delete button
- [x] clicking the delete-button deletes this match or bar from the list
      ​

## Tasks

- [x] create a new feature/deleteAddedBarsAndMatches
- [x] implement the logic for deleting a card which was previously added in [US6](https://github.com/sebastianwel/MatchPal/issues/6) and [US7](https://github.com/sebastianwel/MatchPal/issues/7)
- [x] add minimal styling to the button

**Comment by ThysBat** [comment]
LGTM 🚀
