### ISSUE TITLE
Create review-edit and -deletion logic

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#18]
## Value Proposition

**As a** user
**I want to** be able to edit and delete comments I submitted in the bars-reviews
**so that** I can change or delete my added comments
​

## Description

![image](https://github.com/sebastianwel/MatchPal/assets/130088331/2cf95d73-925c-4b71-bdda-fc9dc80eb078)
​

## Acceptance Criteria

- [x] When being on the reviews-section of a bar in the user-added reviews two buttons should be displayed:
  - [x] one for delete
  - [x] one for edit
- [x] clicking the delete-button removes the review from the list
- [x] clicking the edit-button opens the input form again and focuses it for the user
- [x] clicking on submit again updates the review
      ​

## Tasks

- [x] create a new branch feature/reviewEditAndDelete
- [x] create an edit-button inside of the ReviewCard-component
- [x] create an delete-button inside of the ReviewCard-component
- [x] implement the logic to handle the editing of a user-created review
- [x] implement the logic to handle the deletion of a user-created review
- [x] add minimal styling to both buttons

**Comment by julialoeschel** [comment]
great.

for the delete function, there is an option to assure that the user is not accidentally  deleting the post - a delete modal. 
maybe this is an option to think about in a next small userstory. 

this story is fine for me. good job!

**Comment by sebastianwel** [comment]
aaaaaah, you mean like an "are you sure...." - screen ? This makes sense, I will add this to another US in the end, thanks for the advice and review 😁

**Comment by matschi3** [comment]
Works as expected 🚀
i can't break it

**Comment by sebastianwel** [comment]
Thanks Nils!!
