### ISSUE TITLE
Add a date-filter to the matches page

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#19]
## Value Proposition

**As a** user 
**I want to** be able to filter matches and bars by date
**so that** I can directly see which match took place or will take place in the upcoming days and where I can watch it
​

## Description

![image](https://github.com/sebastianwel/MatchPal/assets/130088331/168c7714-c618-4fda-930d-fd39eba9c585)
​

## Acceptance Criteria

- [ ] a horizontal filter should be displayed below the header
- [ ] the filter should be focused on the current day and be scrollable to go back and forth in the days
- [ ] In the MatchesList only filtered matches by the selected date should be shown
- [ ] clicking on another date in the horizontal filter should update the list with only the matches taking place on the according date
      ​

## Tasks

- [ ] create a feature/addDateFilter branch
- [ ] build a DateFilter component
- [ ] add logic to display only the filtered matches in the MatchesList and bars in the BarsList
- [ ] Import the DateFilter and render it on the both pages
- [ ] style the component accordingly

**Comment by FelineHuhn** [comment]
Hey Sebastian, nice user story and I think this feature is great 🎉I just have some tiny suggestions: 

In your value proposition, the wording behind "**As a** user" you could put behind the second line, or? So it's more written like the common syntax: 
**As a** user
**I want to** be able to filter matches by date on the matches page
**so that** I can directly see which match took place or will take place in the upcoming days

Acceptance criteria: 
- Wouldn't you rather describe the displayed filter as horizontal? 
- The last sentence could be worded a little more clearly, couldn't it?

Tasks: 
- the filter functionality is not mentioned, you could add a bulletpoint like "add logic to display only the filtered matches in the `MatchesList`
- and I'm sure you don't want the `MatchFIlter` component be not only imported but rendered, or?

**Comment by FelineHuhn** [comment]
LGTM now 🚀
