### ISSUE TITLE
Create a map page

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#20]
## Value Proposition

**As a** user
**I want to** be able to open a map-page
**so that** I can see all bars showing a match
​

## Description

![image](https://github.com/sebastianwel/MatchPal/assets/130088331/4ddf242a-26e8-4e5a-ace9-63fcdee6c19e)

## Acceptance Criteria

- [ ] When opening the map-page a map should be displayed
- [ ] On this map, marks should be set, showing the bars that show matches
- [ ] The map should be shown full-sized between the header and footer
- [ ] When scrolling, it should be zoomed out
      ​

## Tasks

- [ ] create a new feature/MapPage branch
- [ ] install the google-maps-react package
- [ ] create a component MapContainer, containing all necessary modules from the google-maps-package
- [ ] create an API-Key and import it into the project
- [ ] set markers by using longitude and latitude from the bars-mock-array
- [ ] add minimal styling to the components
