### ISSUE TITLE
Bars Page with list of bars

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#3]
## Value proposition

As a user
I want to see a list of bars
so that I can browse the bars and see which matches are shown.

## Description

<img width="246" alt="image" src="https://github.com/sebastianwel/MatchPal/assets/130088331/6c899b1f-4800-44c0-abc9-5d18564dbbc2">

## Acceptance criteria

- [x] bars are displayed as cards in a list
- [x] for each bar, the name and the shown matches in this bar are displayed
- [x] for the matches, each team-logo is displayed next to each other, seperated by "vs" to show that this is a match 
- [x] matches are displayed next to each other
- [x] Clicking on the matches-icon in the footer shows the matches page

## Tasks

- [x] Create a feature branch
- [x] Create a bars mock array
- [x] Create a gamesInBars mock array
- [x] Create a headline for the List
- [x] Create a Component "BarCard" for each bar
- [x] Create a Component "BarsList" with bars
- [x] Map the list of bars
- [x] Add a minimal styling to the barCard component
- [x] Add a minimal styling to the barsList component

**Comment by nastiche** [comment]
LGTM 🪄
