### ISSUE TITLE
Add Confirmation Prompt for Deleting Matches and Bars

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#32]
## Value Proposition

**As a** user  
**I want to** be prompted to confirm before deleting matches and bars that I added
**so that** I can avoid accidentally deleting items and have a chance to correct any mistakes.

## Description

To prevent accidental deletion of matches and bars that were added by the user, a confirmation prompt should be displayed before the deletion process.

![image](https://github.com/sebastianwel/MatchPal/assets/130088331/d12cab28-838d-4d02-b779-59f4b9aba7d2)

## Acceptance Criteria

- [ ] When on the match-details-page or bar-details-page, the added items should have a delete button.
- [ ] Clicking the delete button should prompt the user with a confirmation dialogue asking if they are sure they want to delete the item.
- [ ] If the user confirms the deletion, the match or bar should be removed from the list.
- [ ] If the user cancels the deletion, the item should remain in the list.
- [ ] The confirmation prompt should provide a clear and understandable message to confirm the user's intention.

## Tasks

- [ ] Create a new feature branch "deleteConfirmation"
- [ ] Implement the logic to display a confirmation dialogue before deleting a match or bar that was previously added (based on the logic implemented in US6 and US7).
- [ ] Modify the delete button to trigger the confirmation dialogue.
- [ ] Handle the user's response in the confirmation dialogue to proceed with or cancel the deletion.
- [ ] Ensure the deletion is only performed if the user confirms their intention.
- [ ] Apply minimal styling to the confirmation dialogue and delete button for consistency and clarity.

**Comment by MariaRiosNavarro** [comment]
I think the steps are clear and above all the acceptance criteria are very detailed. For me only your  **Value Proposition** seems to be too long, but it is a matter of taste. So I'm fine with the US 🚀

I would put something shorter and simpler, 
As a user 
I want to receive a confirmation of deletion 
so that I don't delete something wrongly
