### ISSUE TITLE
Show Logos instead of team-color

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#35]
## Value Proposition

**As a** user  
**I want to** see the correct team logos for matches and bars on the match, match-details, bar, and bar-details pages
**so that** I can easily identify and associate the matches and bars with their respective teams.

## Description

To improve the user experience, the app should display the correct team logos for matches and bars on the match, match-details, bar, and bar-details pages. This involves updating the mock array to include the correct team logos for each match and bar.

<img width="346" alt="image" src="https://github.com/LukasWeckner/Capstone-Travel/assets/130088331/4623d236-06fe-4b57-baa2-956679a0d6a1">

## Acceptance Criteria

- [ ] Update the matches and bars mock array to include the correct team logos.
- [ ] On the match page, display the correct team logos for each match.
- [ ] On the match-details page, display the correct team logos for the selected match.
- [ ] On the bar page, display the correct team logos for each bar.
- [ ] On the bar-details page, display the correct team logos for the selected bar.

## Tasks

- [ ] Create a feature branch for updating team logos.
- [ ] Update the matches and bars mock array to include the correct team logos.
- [ ] Modify the match and match-details pages to display the correct team logos.
- [ ] Modify the bar and bar-details pages to display the correct team logos.
- [ ] Test the app to ensure that the correct team logos are being displayed on each page.
- [ ] Refine the styling and layout of the pages as needed for optimal presentation of the team logos.
- [ ] Update the documentation or any relevant instructions to reflect the changes made.
- [ ] Ensure that the team logos are consistently displayed and aligned with the respective matches and bars throughout the app.
