### ISSUE TITLE
Details page for matches

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#4]
## Value proposition

As a user
I want to be able to click on a match to see a details page of this match.
So, I can see the selected match and in which bar I can watch it. 

## Description

<img width="232" alt="image" src="https://github.com/sebastianwel/MatchPal/assets/130088331/51361970-8233-41f7-bfb6-ca6763654aa0">

## Acceptance criteria

- [x] when the user clicks on a match on the matches-page, the details page opens
- [x] each match should have its own detail page
- [x] on the details page, a "back" button below the header should bring the user back to the previous page
- [x] Below the "back" button, the match should be displayed with the following details:
    - [x] the date, when the match takes place
    - [x] logo of the home team with the home-teams name below
    - [x] next to the home team logo the away-teams logo with the name below
    - [x] both teams should be seperated with a "-"
    - [x] below the teams, the start-time of the game should be displayed
- [x] Additionally, below the match-details, a list should be shown, containing all bars which show the match

## Tasks

- [x] Create a feature branch
- [x] Create a gamesInBars mock array
- [x] Create a subheading introducing the bars list
- [x] Create a list Component "BarsListInMatches" for the bars list
- [x] Map the bars which show the match
- [x] Add a minimal styling to the BarsInMatchDetails component
- [x] Add a minimal styling to the barsList component

**Comment by nastiche** [comment]
Everything looks clear to me, I think you can implement it like it is.
