### ISSUE TITLE
Details page for bars

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#5]
## Value proposition

As a user
I want to be able to click on a bar to see a details page of this bar.
There, I want to see all matches which this bar shows. 

## Description

<img width="229" alt="image" src="https://github.com/sebastianwel/MatchPal/assets/130088331/d6216e31-0182-4cec-8fdd-39fa64a302d9">

## Acceptance criteria

- [x] when the user clicks on a bar on the bars-page, the details page opens
- [x] each bar should have its own detail page
- [x] on the details page, a "back" button below the header should bring the user back to the previous page
- [x] below the "back" button, the bar name should be displayed
- [x] below the bar, a subheading should introduce a section of upcoming matches in this bar
- [x] upcoming matches should be displayed as a list with a card per match
- [x] each match-card should contain the following details:
    - [x] each team is presented in the order:
        - [x] home at the top, away below
    - [x] the logo is displayed for each team
    - [x] the date and kickoff time of the match is displayed

## Tasks

- [x] Create a feature branch
- [x] Create a gamesInBars mock array
- [x] Create a back-button a the top of the page, pushing to the previous page
- [x] Create a headline with the according bar-name
- [x] Create a subheading introducing the user the upcoming games
- [x] Create a MatchListInBars component to list the matches
- [x] use the MatchCard component to show the matches 
- [x] Map the MatchCards in the MatchListInBars

**Comment by TmWgnr** [comment]
what kind of bar? Navigation bar? .... joke😀

looks really clean and easy to understand. 
in my opinion, you can run with this story ;)
