### ISSUE TITLE
Extend Matches details-page with form

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#6]
## Value Proposition

**As a** user   
**I want to** be able to add bar to bars list in the matches details
**so that** other users can see which bar(s) this match shows

## Description

<img width="212" alt="image" src="https://github.com/sebastianwel/MatchPal/assets/130088331/3c4b3004-9df9-4679-b41c-c6d06d8492bd">
​

## Acceptance Criteria

- [x] at the bottom of the matches-details page, a form should be displayed
- [x] the form contains a dropdown field, containing all bars
- [x] a selected bar can be submitted
- [x] submitting updates the list

## Tasks

- [x] create a feature branch "addMatchForm"
- [x] create a form-component, including a dropdown-input-field and a submit-button
- [x] create the logic for handling the submit event
- [x] the form-component should be rendered in the matches-details page

**Comment by MariaRiosNavarro** [comment]
LGFM 🚀
