### ISSUE TITLE
Extend bar details-page with match form

### ISSUE THREAD

**Issue by sebastianwel** [sebastianwel/MatchPal#7]
## Value Proposition

**As a** user   
**I want to** be able to add a match to bars in the match details-page
**so that** other users can see which matches this bar shows

## Description

<img width="159" alt="image" src="https://github.com/sebastianwel/MatchPal/assets/130088331/6cb3cda6-0d83-4aad-a43f-df3c0b432975">
​

## Acceptance Criteria

- [ ] at the bottom of the bar-details page, a form should be displayed
- [ ] the form contains a dropdown field, containing all matches
- [ ] a selected match can be submitted
- [ ] submitting updates the list

## Tasks

- [ ] create a feature branch "addBarForm"
- [ ] create a form-component, including a dropdown-input-field and a submit-button
- [ ] create the logic for handling the submit event
- [ ] the form-component should be rendered in the bar-details page
